### ISSUE TITLE
pdf

### ISSUE THREAD

**Issue by drew-drew-u** [pku-liang/MAGIS#2]
https://dl.acm.org/doi/10.1145/3620666.3651330

这里的pdf失效了不能下载了，请问可以上传pdf到仓库中吗。

**Comment by Light-of-Hers** [comment]
> https://dl.acm.org/doi/10.1145/3620666.3651330
> 
> 这里的pdf失效了不能下载了，请问可以上传pdf到仓库中吗。

已经上传了，放在 https://github.com/pku-liang/MAGIS/blob/main/media/magis-asplos24-paper.pdf ，或者通过 README 的 [Paper] 连接访问
